BADISVERYOWN/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('statusfeedpage.urls')),
    path('accordion/', include('accordionpage.urls')),
    path('bookcatalogue/', include('bookcataloguepage.urls')),
    path('auth/', include('authenticationpage.urls'))
]

accordionpage/urls.py
from . import views
from django.urls import path

app_name='accordionpage'

urlpatterns = [
    path('', views.accordion, name='accordion'),
    path('jqueryui/', views.accordion_jqueryui, name='accordion_jqueryui')
]

templates/accordionpage-templates/accordion-jqueryui-base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!----------------------------------Bootstrap + Custom------------------------------------>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!--------------------Google Fonts (kalo perlu ditambahin, tambah aja)-------------------->
    <link href="https://fonts.googleapis.com/css?family=Lato|Rubik|Rubik+Mono+One&display=swap" rel="stylesheet">
    <!-----------------------------------CSS & Styelsheet------------------------------------->
    <link rel="stylesheet" href="{% static '/application-base.css' %}">
    <link rel="stylesheet" href="{% static '/homepage-nav.css' %}">
    <!--------------------------------------jQuery UI----------------------------------------->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <!-----------------------------------------Title------------------------------------------>
    <link rel="shortcut icon" href="{% static 'base-assets/favicon-moon.png' %}" type="image/x-icon">
    <title>{% block title %}{% endblock %}</title>
    {% block style %}{% endblock %}
</head>
<body>
    {% block head_script %}{% endblock %}

    {% block content %}

    {% endblock %}

    <!-------------------------------------Scripts-------------------------------------------->
    {% block script %}{% endblock %}
</body>
</html>

templates/accordionpage-templates/accordion-jqueryui.html
<!DOCTYPE html>

{% extends 'accordionpage-templates/accordion-jqueryui-base.html' %}

{% load static %}

{% block title %}accordion | badi's very own accordion showcase{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'accordionpage-static/accordion-jqueryui.css' %}">
{% endblock %}

{% block head_script %}
    <script type="text/javascript" src="{% static 'accordionpage-static/accordion-jqueryui.js' %}"></script>
{% endblock %}

<!------ Content goes here ------>
{% block content %}

{% include 'homepage-nav.html' %}
    <div id="accordion">
        <div class="group">
          <h3>Section 1</h3>
          <div>
            <p>Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.</p>
          </div>
        </div>
        <div class="group">
          <h3>Section 2</h3>
          <div>
            <p>Sed non urna. Donec et ante. Phasellus eu ligula. Vestibulum sit amet purus. Vivamus hendrerit, dolor at aliquet laoreet, mauris turpis porttitor velit, faucibus interdum tellus libero ac justo. Vivamus non quam. In suscipit faucibus urna. </p>
          </div>
        </div>
        <div class="group">
          <h3>Section 3</h3>
          <div>
            <p>Nam enim risus, molestie et, porta ac, aliquam ac, risus. Quisque lobortis. Phasellus pellentesque purus in massa. Aenean in pede. Phasellus ac libero ac tellus pellentesque semper. Sed ac felis. Sed commodo, magna quis lacinia ornare, quam ante aliquam nisi, eu iaculis leo purus venenatis dui. </p>
            <ul>
              <li>List item one</li>
              <li>List item two</li>
              <li>List item three</li>
            </ul>
          </div>
        </div>
        <div class="group">
          <h3>Section 4</h3>
          <div>
            <p>Cras dictum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean lacinia mauris vel est. </p><p>Suspendisse eu nisl. Nullam ut libero. Integer dignissim consequat lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. </p>
          </div>
        </div>
      </div>

{% endblock %}

templates/accordionpage-templates/accordion.html
<!DOCTYPE html>

{% extends 'application-base.html' %}

{% load static %}

{% block title %}accordion | badi's very own accordion showcase{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'accordionpage-static/accordion.css' %}">
{% endblock %}

<!------ Content goes here ------>
{% block content %}
{% include 'homepage-nav.html' %}


<section id="title-section" class="text-center">
    <h3>accordion ala ala</h3>
</section>

<section id="accordion-section" class=".accordion-wrapper text-center pr-5 pl-5">

    <div id="accordion-1" class="accordion my-4">
        <div id="main-card-1" class="main-card d-flex py-1 pt-2 px-4">
            <h2 class="d-inline-block mr-auto">aktivitas saat ini</h2>
            <div class="arrow-icons">
                <a class="button-up"><i class="fa fa-chevron-up fa-1x d-inline mx-1" aria-hidden="true"></i></a>
                <a class="button-down"><i class="fa fa-chevron-down fa-1x d-inline mx-1" aria-hidden="true"></i></a>
            </div>
        </div>
        <div id="sub-card-1" class="active sub-card px-5">
            <p>nonton drakor lah gilak ngapain lg 5 bulan liburrrr</p>
        </div>
    </div>



    <div id="accordion-2" class="accordion my-4">
        <div id="main-card-2" class="main-card d-flex py-1 pt-2 px-4">
            <h2 class="d-inline-block mr-auto">pengalaman organisasi/kepanitiaan</h2>
            <div class="arrow-icons">
                <a class="button-up"><i class="fa fa-chevron-up fa-1x d-inline mx-1" aria-hidden="true"></i></a>
                <a class="button-down"><i class="fa fa-chevron-down fa-1x d-inline mx-1" aria-hidden="true"></i></a>
            </div>
        </div>
        <div id="sub-card-2" class="sub-card px-5">
            <p>banyak dah sibuk bgt pokoknyaaa gamuatttt</p>
        </div>
    </div>



    <div id="accordion-3" class="accordion my-4">
        <div id="main-card-3" class="main-card d-flex py-1 pt-2 px-4">
            <h2 class="d-inline-block mr-auto">prestasi</h2>
            <div class="arrow-icons">
                <a class="button-up"><i class="fa fa-chevron-up fa-1x d-inline mx-1" aria-hidden="true"></i></a>
                <a class="button-down"><i class="fa fa-chevron-down fa-1x d-inline mx-1" aria-hidden="true"></i></a>
            </div>
        </div>
        <div id="sub-card-3" class="sub-card px-5">
            <p>gaada :(</p>
        </div>
    </div>



    <div id="accordion-4" class="accordion my-4">
        <div id="main-card-4" class="main-card d-flex py-1 pt-2 px-4">
            <h2 class="d-inline-block mr-auto">film favorit</h2>
            <div class="arrow-icons">
                <a class="button-up"><i class="fa fa-chevron-up fa-1x d-inline mx-1" aria-hidden="true"></i></a>
                <a class="button-down"><i class="fa fa-chevron-down fa-1x d-inline mx-1" aria-hidden="true"></i></a>
            </div>
        </div>
        <div id="sub-card-4" class="sub-card px-5">
            <p>weeei follow <a href="http://letterboxd.com/fahdikrie" target="_blank">letterboxd</a> guaaaa ayo kita mutualan</p>
        </div>
    </div>

</section>

<!-- <section id="button-section" class="text-center">
    <a href="{% url 'accordionpage:accordion_jqueryui' %}" class="toggle_color btn btn-secondary">check my jqueryui accordion too</a>
</section> -->


{% endblock %}

{% block script %}
    <script src="{% static 'accordionpage-static/accordion.js' %}"></script>
{% endblock %}