BADISVERYOWN/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('statusfeedpage.urls')),
    path('accordion/', include('accordionpage.urls')),
    path('bookcatalogue/', include('bookcataloguepage.urls')),
    path('auth/', include('authenticationpage.urls'))
]

authenticationpage/urls.py
import django.contrib.auth
from django.urls import path, include
from . import views

app_name = 'authenticationpage'

urlpatterns = [
    path('login/', views.login_views, name='login'),
    path('signup/', views.sign_up_views, name='signup'),
    path('logout/', views.logout_views, name='logout'),
    path('welcome/<str:username>', views.welcome_views, name='welcome')
]

'''
in case kalo mau pake builtin django auth urls
'''
# urlpatterns += [
#     path('accounts/', include('django.contrib.auth.urls')),
# ]

'''
jadinya /auth/accounts/ + (login, logout, password_change, etc.)
'''

statusfeedpage/urls.py
from . import views
from django.urls import path

app_name='statusfeedpage'

urlpatterns = [
    path('', views.status_feed, name='status_feed'),
    path('confirmation/<str:status>/<str:posted_by>', views.status_feed_confirmation, name='status_feed_confirmation'),
    path('change_color/<int:id>', views.status_feed_change_color, name='status_feed_change_color')
]

templates/authenticationpage-templates/login.html
<!DOCTYPE html>

{% extends 'application-base.html' %}

{% load static %}

{% block title %}login | badi's very own login page{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'authenticationpage-static/login.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;1,300;1,400&display=swap" rel="stylesheet">
{% endblock %}

<!------ Content goes here ------>
{% block content %}
{% include 'homepage-nav.html' %}

<section id="title-section" class="text-center">
    <h3>Login Page</h3>
</section>

<section id="form-section" class="text-center">
    <form method="POST" action="/auth/login/">
        {% csrf_token %}
        <div id="input-section">
            {% for field in form %}
            <span><p class="errors">{{ field.errors }}</p></span>
            <p class="text-left">{{ field.label_tag }} <br></p>
            <span class="">{{ field }}</span>
            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        {% endfor %}
        </div>
        <button type="submit" class="btn btn-success button" name="login">Login</button>
    </form>
</section>

<section id="info-section" class="text-center">
    <h5>or perhaps... you don't have an account yet? <span><a href="{% url 'authenticationpage:signup' %}">sign up first</a></span></h5>
</section>

{% endblock %}

templates/authenticationpage-templates/signup.html
<!DOCTYPE html>

{% extends 'application-base.html' %}

{% load static %}

{% block title %}sign up | badi's very own sign up page{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'authenticationpage-static/signup.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;1,300;1,400&display=swap" rel="stylesheet">
{% endblock %}

<!------ Content goes here ------>
{% block content %}
{% include 'homepage-nav.html' %}

<section id="title-section" class="text-center">
    <h3>Sign Up Page</h3>
</section>

<section id="form-section" class="text-left">
    <form method="POST" action="/auth/signup/">
        {% csrf_token %}
        <div id="input-section">
            {% for field in form %}
                <div class="input-wrapper">
                    <span><p class="errors">{{ field.errors }}</p></span>
                    <p class="text-left">{{ field.label_tag }} <br></p>
                    <span class="">{{ field }}</span>
                    {% if field.help_text %}
                    <p class="help text-left ml-3">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
        <button type="submit" id="signup-btn" class="btn btn-success button" name="sign-up">Sign Up</button>
    </form>
</section>

<section id="info-section" class="text-center">
    <h5>already have an account? <span><a href="{% url 'authenticationpage:login' %}">login</a></span></h5>
</section>

{% endblock %}

templates/authenticationpage-templates/welcome.html
<!DOCTYPE html>

{% extends 'application-base.html' %}

{% load static %}

{% block title %}welcome | badi's very own welcome page{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'authenticationpage-static/welcome.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;1,300;1,400&display=swap" rel="stylesheet">
{% endblock %}

<!------ Content goes here ------>
{% block content %}
{% include 'homepage-nav.html' %}

<section id="title-section" class="text-center">

    <h3><span id="welcome-tag">welcome</span>, {{ username }}</h3>
    <h5>you will be redirected to the landing page in <span id="countdown-timer">8</span> seconds, <br>
    or you might as well <span><a href="{% url 'statusfeedpage:status_feed' %}">go now</a></span> i guess... yeaaa you do you mate</h5>

</section>

{% endblock %}

{% block script %}
    <script src="{% static 'authenticationpage-static/welcome.js' %}"></script>
{% endblock %}