BADISVERYOWN/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('statusfeedpage.urls')),
    path('accordion/', include('accordionpage.urls')),
    path('bookcatalogue/', include('bookcataloguepage.urls')),
    path('auth/', include('authenticationpage.urls'))
]

accordionpage/urls.py
from . import views
from django.urls import path

app_name='accordionpage'

urlpatterns = [
    path('', views.accordion, name='accordion'),
    path('jqueryui/', views.accordion_jqueryui, name='accordion_jqueryui')
]

authenticationpage/urls.py
import django.contrib.auth
from django.urls import path, include
from . import views

app_name = 'authenticationpage'

urlpatterns = [
    path('login/', views.login_views, name='login'),
    path('signup/', views.sign_up_views, name='signup'),
    path('logout/', views.logout_views, name='logout'),
    path('welcome/<str:username>', views.welcome_views, name='welcome')
]

'''
in case kalo mau pake builtin django auth urls
'''
# urlpatterns += [
#     path('accounts/', include('django.contrib.auth.urls')),
# ]

'''
jadinya /auth/accounts/ + (login, logout, password_change, etc.)
'''

bookcataloguepage/urls.py
from . import views
from django.urls import path, re_path

app_name='bookcataloguepage'

urlpatterns = [
    path('', views.bookcatalogue, name='bookcatalogue'),
    re_path(r'^apilikedbook/$', views.LikedBookViews.as_view()),
    path('apilikedbook/<int:pk>/', views.LikedBookSingleViews.as_view())
]

statusfeedpage/urls.py
from . import views
from django.urls import path

app_name='statusfeedpage'

urlpatterns = [
    path('', views.status_feed, name='status_feed'),
    path('confirmation/<str:status>/<str:posted_by>', views.status_feed_confirmation, name='status_feed_confirmation'),
    path('change_color/<int:id>', views.status_feed_change_color, name='status_feed_change_color')
]

templates/application-base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!----------------------------------Bootstrap + Custom------------------------------------>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!--------------------Google Fonts (kalo perlu ditambahin, tambah aja)-------------------->
    <script src="https://kit.fontawesome.com/a5686a1bdd.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&family=Rubik:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <!-----------------------------------CSS & Styelsheet------------------------------------->
    <link rel="stylesheet" href="{% static '/application-base.css' %}">
    <link rel="stylesheet" href="{% static '/homepage-nav.css' %}">
    <!-----------------------------------------Title------------------------------------------>
    <link rel="shortcut icon" href="{% static 'base-assets/favicon-moon.png' %}" type="image/x-icon">
    <title>{% block title %}{% endblock %}</title>
    {% block style %}{% endblock %}
</head>
<body>
    {% block head_script %}{% endblock %}

    {% block content %}

    {% endblock %}
    <!-------------------------------------Scripts-------------------------------------------->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    {% block script %}{% endblock %}
</body>
</html>

templates/application-nav.html
<!DOCTYPE html>

<nav>
    <nav class="navbar container">
        <a class="navbar-brand" href="{% url 'homepage' %}"><h1>BADI.</h1></a>

        <div class="nav-item">
            <a href="{% url 'blog' %}" id="nav-icons1" data-toggle="tooltip" data-placement="bottom" title="activities">
                <i class="fas fa-user-astronaut fa-2x ml-3" style="color: yellow;"><span class="nav-desc" id="nav-desc1" style="float: right;">activities</span></i> 
            </a>

            <a href="{% url 'blog' %}" id="nav-icons2" data-toggle="tooltip" data-placement="bottom" title="blog">
                <i class="fas fa-globe-africa fa-2x ml-3" style="color: yellow;"><span class="nav-desc" id="nav-desc2" style="float: right;">blog</span></i> 
            </a>
        </div>
    </nav>
</nav>

templates/homepage-nav.html
<!DOCTYPE html>

<nav id="navigation-bar">
    <div id="navbar-brand">
        <h3><a href="https://badisveryown.herokuapp.com/">B</a></h3>
    </div>

    <div id="navbar-items">
        <ul class="list-inline">
            <li class="list-inline-item ml-5">
                <h2><a href="https://badisveryown.herokuapp.com/#secondPage/">About</a></h2>
            </li>

            <li class="list-inline-item ml-5">
                <h2><a href="https://badisveryown.herokuapp.com/">Activities</a></h2>
            </li>

            <li class="list-inline-item ml-5">
                <h2><a href="https://badisveryown.herokuapp.com/blog/">Blog</a></h2>
            </li>

            <li class="list-inline-item active dropdown ml-4">
                <h2><a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Credentials</a></h2>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <li><a class="dropdown-item" href="https://badisveryown.herokuapp.com/#thirdPage/"><span class="nav-dropdown-items">Portfolio</span></a></li>
                    <li><a class="dropdown-item" href="https://drive.google.com/file/d/1OU3FW9TYOq70LjPKP1rqNOPta4xeLwjA/view?usp=sharing" target="_blank"><span class="nav-dropdown-items">Resume</span></a></li>
                    <li><a class="dropdown-item" href="https://badisveryown.herokuapp.com/#fifthPage"><span class="nav-dropdown-items">Contacts</span></a></li>
                </ul>
            </li>

            <li class="list-inline-item active dropdown mr-2">
                <h2><a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Stories</a></h2>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink2">
                    <li><a class="dropdown-item" href="https://badisveryown.herokuapp.com/story/"><span class="nav-dropdown-items">Story 1 s/d 3</span></a></li>
                    <li><a class="dropdown-item" href="https://badisveryown.herokuapp.com/datetime/"><span class="nav-dropdown-items">Date & Time</span></a></li>
                    <li><a class="dropdown-item" href="https://badisveryown.herokuapp.com/schedule/"><span class="nav-dropdown-items">Schedule</span></a></li>
                    <li><a class="dropdown-item" href="https://badisveryown.herokuapp.com/event/"><span class="nav-dropdown-items">Events</span></a></li>
                    <li><a class="dropdown-item" href="{% url 'statusfeedpage:status_feed' %}"><span class="nav-dropdown-items">Status</span></a></li>
                    <li><a class="dropdown-item" href="{% url 'accordionpage:accordion' %}"><span class="nav-dropdown-items">Accordion</span></a></li>
                    <li><a class="dropdown-item" href="{% url 'bookcataloguepage:bookcatalogue' %}"><span class="nav-dropdown-items">Book Catalogue</span></a></li>
                    <li><a class="dropdown-item" href="{% url 'authenticationpage:login' %}" target="_blank"><span class="nav-dropdown-items">Login</span></a></li>
                </ul>
            </li>

            <li class="list-inline-item">
                <h2 style="font-size: 1.5em; font-weight: 500; font-family: 'Rubik Light';">|</h2>
            </li>

            {% if not request.user.is_authenticated %}
            <li class="list-inline-item ml-3">
                <h2><a class="d-inline" href="{% url 'authenticationpage:login' %}"><i class="fas fa-user-circle fa-1x d-inline mr-2"></i>Log in</a></h2>
            </li>
            {% else %}
            <li class="list-inline-item active dropdown ml-1">
                <h2><a class="nav-link dropdown-toggle d-inline" id="navbarDropdownMenuLink3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-circle fa-1x d-inline mr-2"></i>{{ request.user }}</a></h2>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink3">
                    <li><a class="dropdown-item" href="{% url 'authenticationpage:logout' %}"><span class="nav-dropdown-items">Logout</span></a></li>
                </ul>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>