BADISVERYOWN/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('statusfeedpage.urls')),
    path('accordion/', include('accordionpage.urls')),
    path('bookcatalogue/', include('bookcataloguepage.urls')),
    path('auth/', include('authenticationpage.urls'))
]

statusfeedpage/urls.py
from . import views
from django.urls import path

app_name='statusfeedpage'

urlpatterns = [
    path('', views.status_feed, name='status_feed'),
    path('confirmation/<str:status>/<str:posted_by>', views.status_feed_confirmation, name='status_feed_confirmation'),
    path('change_color/<int:id>', views.status_feed_change_color, name='status_feed_change_color')
]

templates/statusfeedpage-templates/confirmation.html
<!DOCTYPE html>

{% extends 'application-base.html' %}

{% load static %}

{% block title %}feed | badi's very own feed page{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'statusfeedpage-static/confirmation.css' %}">
{% endblock %}

<!------ Content goes here ------>
{% block content %}
{% include 'homepage-nav.html' %}

<div class="text-center">
    
    <section id="title-section"> 
        <h3>are u suuuuuuuure</h3>
    </section>


    <p>you said <em>"{{ status }}"</em> and you said your name was <em>"{{ posted_by }}"</em></p>

    <section id="form-section">
        <form method="POST" action="{% url 'statusfeedpage:status_feed_confirmation' posted_by status %}">
            {% csrf_token %}
            <button id="confirm" type="submit" class="btn btn-success">submit</button>
            <a id="decline" href="{% url 'statusfeedpage:status_feed' %}" class="btn btn-outline-danger">nonono</a>
        </form>
    </section>


</div>

{% endblock %}

templates/statusfeedpage-templates/feed.html
<!DOCTYPE html>

{% extends 'application-base.html' %}

{% load static %}

{% block title %}feed | badi's very own feed page{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'statusfeedpage-static/feed.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;1,300;1,400&display=swap" rel="stylesheet">
{% endblock %}

<!------ Content goes here ------>
{% block content %}
{% include 'homepage-nav.html' %}

<section id="title-section" class="text-center">
    <h3>(What's The Story) Morning Glory?</h3>
</section>

<section id="form-section">
    <form method="POST" action="{% url 'statusfeedpage:status_feed' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button id="submit" type="submit" class="btn btn-success">submit</button>
    </form>
</section>

<section id="statuses-section">
{% for i in posted_statuses %}
    <div class="bubble statuses-card" style="background-color: {{ i.color }};">
        <span class="status"><p>{{ i.status }}</p></span>
        <p>posted by <em>{{ i.posted_by }}</em> at <em>{{ i.datetime }}</em></p>

        <a href="{% url 'statusfeedpage:status_feed_change_color' i.id %}" class="toggle_color btn btn-failure">change color</a>
    </div>
{% endfor %}

</section>

{% endblock %}